/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingInput = IDL.Record({
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'location' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const ListingId = IDL.Nat;
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'location' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func([ListingInput], [Listing], []),
  'deactivateListing' : IDL.Func([ListingId], [], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ListingId], [Listing], ['query']),
  'getListingsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateListing' : IDL.Func([ListingId, ListingInput], [Listing], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingInput = IDL.Record({
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'location' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const ListingId = IDL.Nat;
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'location' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func([ListingInput], [Listing], []),
    'deactivateListing' : IDL.Func([ListingId], [], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ListingId], [Listing], ['query']),
    'getListingsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateListing' : IDL.Func([ListingId, ListingInput], [Listing], []),
  });
};

export const init = ({ IDL }) => { return []; };