/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Listing {
  'id' : ListingId,
  'title' : string,
  'contactInfo' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'unit' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'price' : number,
  'location' : string,
  'images' : Array<string>,
}
export type ListingId = bigint;
export interface ListingInput {
  'title' : string,
  'contactInfo' : string,
  'unit' : string,
  'description' : string,
  'category' : string,
  'price' : number,
  'location' : string,
  'images' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<[ListingInput], Listing>,
  'deactivateListing' : ActorMethod<[ListingId], undefined>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[ListingId], Listing>,
  'getListingsByOwner' : ActorMethod<[Principal], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateListing' : ActorMethod<[ListingId, ListingInput], Listing>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];